# Generated by Django 2.2.6 on 2019-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblogusers',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is activated?'),
        ),
        migrations.AddField(
            model_name='myblogusers',
            name='send_messages',
            field=models.BooleanField(default=True, verbose_name='send messages?'),
        ),
    ]
