# Generated by Django 2.2.6 on 2019-11-04 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191103_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('71e49b6a-99fd-4170-a2d7-9014e246d9b5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('post', models.ManyToManyField(to='post.Post')),
            ],
        ),
    ]
