# Generated by Django 2.2.6 on 2019-11-04 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191104_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='post',
            field=models.ManyToManyField(related_name='hash_tag', to='post.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ab22e967-2472-4663-8998-b31f2415bfbf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
